/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Car;
import model.Carlist;

/**
 *
 * @author sethu
 */
public class ViewPanel extends javax.swing.JPanel {

    private JPanel rightPanel;
    Carlist myCarList;
    private Integer selectedCarIndex;
    /**
     * Creates new form ViewPanel
     */
    public ViewPanel(JPanel myJPanel, Carlist myCarList, Integer index) {
        initComponents();
        
//        myCarList = new Carlist();
        this.myCarList = myCarList;
        rightPanel = myJPanel;
        selectedCarIndex = index;
        
        populateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblLicense = new javax.swing.JLabel();
        lblMaintanenceCert = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        lblManufacturedYear = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        btnAvailabilityYes = new javax.swing.JRadioButton();
        btnAvailabilityNo = new javax.swing.JRadioButton();
        btnMaintanenceValid = new javax.swing.JRadioButton();
        btnMaintanenceExpired = new javax.swing.JRadioButton();
        dateManufacturedYear = new com.toedter.calendar.JYearChooser();
        txtCompany = new javax.swing.JTextField();
        txtModelName = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtLicense = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("VIEW / EDIT CAR");

        lblCompany.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCompany.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCompany.setText("Company : ");

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Model Name : ");

        lblSerialNumber.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerialNumber.setText("Serial Number : ");

        lblSeats.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSeats.setText("No. of Seats : ");

        lblCity.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("City : ");

        lblLicense.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblLicense.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLicense.setText("License Plate No. : ");

        lblMaintanenceCert.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblMaintanenceCert.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaintanenceCert.setText("Maintanence Certificate : ");

        lblAvailability.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblAvailability.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAvailability.setText("Availability : ");

        lblManufacturedYear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblManufacturedYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblManufacturedYear.setText("Manufactured Year : ");

        lblModelNumber.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblModelNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelNumber.setText("Model Number : ");

        btnAvailabilityYes.setText("Yes");
        btnAvailabilityYes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnAvailabilityYesItemStateChanged(evt);
            }
        });

        btnAvailabilityNo.setText("No");
        btnAvailabilityNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnAvailabilityNoItemStateChanged(evt);
            }
        });

        btnMaintanenceValid.setText("Valid");
        btnMaintanenceValid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnMaintanenceValidItemStateChanged(evt);
            }
        });

        btnMaintanenceExpired.setText("Expired");
        btnMaintanenceExpired.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnMaintanenceExpiredItemStateChanged(evt);
            }
        });
        btnMaintanenceExpired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaintanenceExpiredActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnBack.setText("<- Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnBack)
                .addGap(13, 13, 13)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnEdit))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMaintanenceCert, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnMaintanenceValid, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnMaintanenceExpired, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnAvailabilityYes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnAvailabilityNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(dateManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(btnCancel)
                .addGap(5, 5, 5)
                .addComponent(btnUpdate))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(btnEdit))))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaintanenceCert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaintanenceValid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaintanenceExpired, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAvailabilityYes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvailabilityNo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel)
                    .addComponent(btnUpdate)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvailabilityYesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnAvailabilityYesItemStateChanged
        // TODO add your handling code here:
        btnAvailabilityNo.setSelected(!btnAvailabilityYes.isSelected());
    }//GEN-LAST:event_btnAvailabilityYesItemStateChanged

    private void btnAvailabilityNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnAvailabilityNoItemStateChanged
        // TODO add your handling code here:
        btnAvailabilityYes.setSelected(!btnAvailabilityNo.isSelected());
    }//GEN-LAST:event_btnAvailabilityNoItemStateChanged

    private void btnMaintanenceValidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnMaintanenceValidItemStateChanged
        // TODO add your handling code here:
        btnMaintanenceExpired.setSelected(!btnMaintanenceValid.isSelected());
    }//GEN-LAST:event_btnMaintanenceValidItemStateChanged

    private void btnMaintanenceExpiredItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnMaintanenceExpiredItemStateChanged
        // TODO add your handling code here:
        btnMaintanenceValid.setSelected(!btnMaintanenceExpired.isSelected());
    }//GEN-LAST:event_btnMaintanenceExpiredItemStateChanged

    private void btnMaintanenceExpiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaintanenceExpiredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaintanenceExpiredActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        Car newCar = new Car();
        Boolean isValid = checkForValidations();
        if (isValid) {
            newCar.setCompany(txtCompany.getText().toLowerCase());
            newCar.setModelName(txtModelName.getText().toLowerCase());
            newCar.setModelNumber(Double.parseDouble(txtModelNumber.getText()));
            newCar.setSerialNumber(Double.parseDouble(txtSerialNumber.getText()));
            newCar.setSeats(Integer.parseInt(txtSeats.getText()));
            newCar.setCity(txtCity.getText().toLowerCase());
            newCar.setNumberPlate(txtLicense.getText().toLowerCase());
            newCar.setManufacturedYear(dateManufacturedYear.getYear());
            if (btnAvailabilityYes.isSelected()) {
                newCar.setAvailability(true);
            } else if (btnAvailabilityNo.isSelected()) {
                newCar.setAvailability(false);
            }
            if (btnMaintanenceValid.isSelected()) {
                newCar.setMaintenance(true);
            } else if (btnMaintanenceExpired.isSelected()) {
                newCar.setMaintenance(false);
            }
            
            myCarList.modifyCar(selectedCarIndex, newCar); // adding to the array
            JOptionPane.showMessageDialog(this, "Car Information Saved");
            rightPanel.remove(this);
            CardLayout layout = (CardLayout) rightPanel.getLayout();
            layout.previous(rightPanel);
//            clearInputs();
        } else {
            JOptionPane.showMessageDialog(this,"Some fields are incorrect, Please check");
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAvailabilityNo;
    private javax.swing.JRadioButton btnAvailabilityYes;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JRadioButton btnMaintanenceExpired;
    private javax.swing.JRadioButton btnMaintanenceValid;
    private javax.swing.JButton btnUpdate;
    private com.toedter.calendar.JYearChooser dateManufacturedYear;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblMaintanenceCert;
    private javax.swing.JLabel lblManufacturedYear;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtModelName;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables

    private void populateData() {
        // show the data here
        Car selectedCar = myCarList.getCar(selectedCarIndex);
        txtCompany.setText(selectedCar.getCompany());
        txtModelName.setText(selectedCar.getModelName());
        txtSerialNumber.setText(selectedCar.getSerialNumber().toString());
        txtModelNumber.setText(selectedCar.getModelNumber().toString());
        txtCity.setText(selectedCar.getCity());
        txtSeats.setText(String.valueOf(selectedCar.getSeats()));
        dateManufacturedYear.setYear(selectedCar.getManufacturedYear());
        txtLicense.setText(selectedCar.getNumberPlate());
        btnAvailabilityYes.setSelected(selectedCar.getAvailability());
        btnAvailabilityNo.setSelected(!selectedCar.getAvailability());
        btnMaintanenceValid.setSelected(selectedCar.getMaintenance());
        btnMaintanenceExpired.setSelected(!selectedCar.getMaintenance());

    }

    private Boolean checkForValidations() {
        return true;
    }
}
