/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Restaurant.MenuItem;
import Business.Restaurant.Restaurant;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sethu
 */
public class CreateMenuItem extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem ecosystem;
    Restaurant restaurant;
    MenuItem menuItem;
    /**
     * Creates new form CreateMenuItem
     */
    public CreateMenuItem(JPanel userProcessContainer,EcoSystem ecosystem, Restaurant restaurant, MenuItem menuItem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.restaurant = restaurant;
        this.menuItem = menuItem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD / EDIT MENU ITEM");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 42));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 83, 91, 35));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 83, 142, 35));
        add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 129, 142, 35));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Description : ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 129, 91, 35));
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 175, 142, 35));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Quantity (LBS) : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 175, 91, 35));
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 221, 142, 35));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Price ($) : ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 221, 91, 35));

        btnSave.setForeground(new java.awt.Color(0, 51, 204));
        btnSave.setText("💾 Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 312, -1, -1));

        btnCancel.setForeground(new java.awt.Color(255, 0, 0));
        btnCancel.setText("❌ Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 312, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
            String name = txtName.getText();
            String description = txtDescription.getText();
            Double quantity = Double.parseDouble(txtWeight.getText());
            Double cost = Double.parseDouble(txtPrice.getText());
        if (menuItem == null) {
            // check quanity and cost are numbers or not
            if(restaurant.checkUniqueMenuItemName(name)) {
                MenuItem newMenuItem = new MenuItem();
                newMenuItem.setName(name);
                newMenuItem.setDescription(description);
                newMenuItem.setQuantity(quantity);
                newMenuItem.setCost(cost);

                restaurant.getMenu().add(newMenuItem); // adds menu item
                goBack();
            } else {
                // failed
                JOptionPane.showMessageDialog(this, "Menu Item with same name already exists in the restaurant");
                return;
            }   
        } else {
            // edit object (name is not changeble)
            MenuItem newMenuItem = new MenuItem();
            newMenuItem.setName(name);
            newMenuItem.setDescription(description);
            newMenuItem.setQuantity(quantity);
            newMenuItem.setCost(cost);
            
            int index = restaurant.getMenu().indexOf(menuItem);
            restaurant.getMenu().set(index, newMenuItem); // replace the existing object
            goBack();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        if (menuItem == null) {
            // it means it is create
        } else {
            // it is edit
            PopulateMenu(menuItem);
        }
    }//GEN-LAST:event_formComponentShown

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        goBack();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

    private void PopulateMenu(MenuItem menuItem) {
        txtName.setText(menuItem.getName());
        txtDescription.setText(menuItem.getDescription());
        txtWeight.setText(String.valueOf(menuItem.getQuantity()));
        txtPrice.setText(String.valueOf(menuItem.getCost()));
        txtName.setEditable(false);
    }

    private void goBack() {
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }
}
