/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.City;
import model.Community;
import model.House;

/**
 *
 * @author sethu
 */
public class CreateHouse extends javax.swing.JPanel {

    private JPanel rightPanel;
    private City city;
    private Community selectedCommunity;
    /**
     * Creates new form CreateHouse
     */
    public CreateHouse(JPanel rightPanel, City city, Community selectedCommunity) {
        initComponents();
        this.rightPanel = rightPanel;
        this.city = city;
        this.selectedCommunity = selectedCommunity;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblHouseNumber = new javax.swing.JLabel();
        txtHouseNumber = new javax.swing.JTextField();
        txtStreetName = new javax.swing.JTextField();
        lblStreetName = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        lblZip = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Kristen ITC", 3, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create New House");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, 615, 50));

        lblHouseNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHouseNumber.setText("House Number : ");
        add(lblHouseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, 94, 42));
        add(txtHouseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 117, 468, 42));
        add(txtStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 191, 468, 42));

        lblStreetName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStreetName.setText("Street Name : ");
        add(lblStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 191, 94, 42));
        add(txtZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 263, 468, 42));

        lblZip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblZip.setText("Zip : ");
        add(lblZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 263, 94, 42));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 392, -1, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 392, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        House newHouse = new House();
        newHouse.setHouseNumber(Integer.parseInt(txtHouseNumber.getText()));
        newHouse.setStreetName(txtStreetName.getText());
        newHouse.setZipCode(Long.parseLong(txtZip.getText()));
        
        for(House h: selectedCommunity.getHousesList()){ // checking for the same house entered twice
            if (h.getHouseNumber() == newHouse.getHouseNumber() && h.getStreetName().equals(newHouse.getStreetName()) && h.getZipCode() == newHouse.getZipCode()) {
                JOptionPane.showMessageDialog(this, "The House information is already entered");
                return;
            }
        }
        
        for (Community c: city.getCommunities()){
            if (!c.getName().equals(selectedCommunity.getName())) {
                for (House h:c.getHousesList()){
                    if (h.getZipCode() == newHouse.getZipCode()) {
                        JOptionPane.showMessageDialog(this, "Two different Communities cannot have same zipcode, Community " +c.getName()+" has the same zipcode");
                        return;
                    }
                }
            }
        }
        
        
        
       Community newCommunity = selectedCommunity;
       newCommunity.add(newHouse); // adding a house to selectedCommunity
        
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel); 
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
      rightPanel.remove(this);
      CardLayout layout = (CardLayout) rightPanel.getLayout();
      layout.previous(rightPanel); 
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblHouseNumber;
    private javax.swing.JLabel lblStreetName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTextField txtHouseNumber;
    private javax.swing.JTextField txtStreetName;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
