/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.Community;
import model.House;
import model.PatientsList;
import model.Person;
import model.PersonsList;

/**
 *
 * @author sethu
 */
public class ViewPatients extends javax.swing.JPanel {

    public City city;
    public JPanel rightPanel;
    public PersonsList personsList;
    public PatientsList patientsList;
    /**
     * Creates new form ViewPatients
     */
    public ViewPatients(JPanel rightPanel, City city, PersonsList personsList, PatientsList patientsList) {
        initComponents();
        this.city = city;
        this.rightPanel = rightPanel;
        this.personsList = personsList;
        this.patientsList = patientsList;
        
        populateTable(personsList);
        populateFilter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientsTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        selCommunity = new javax.swing.JComboBox<>();
        lblBloodPressure = new javax.swing.JLabel();
        txtBloodPressure = new javax.swing.JTextField();
        btnApplyFilter = new javax.swing.JButton();
        btnCancelFilter = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEdit.setBackground(new java.awt.Color(0, 102, 102));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("View Encounters");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 416, -1, -1));

        patientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Sex", "Patient ID", "Blood Pressure", "Rec. Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(patientsTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 234, 594, 171));

        btnBack.setBackground(new java.awt.Color(255, 51, 51));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, -1));

        title.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Filters");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 18, 339, 27));

        title1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("List of Patients");
        add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 188, 308, 35));

        lblCommunity.setForeground(new java.awt.Color(255, 255, 255));
        lblCommunity.setText("Community");
        add(lblCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 63, 90, 26));

        selCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(selCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 63, 104, 26));

        lblBloodPressure.setForeground(new java.awt.Color(255, 255, 255));
        lblBloodPressure.setText("Blood Pressure  > ");
        add(lblBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 100, -1, 26));
        add(txtBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 104, 26));

        btnApplyFilter.setBackground(new java.awt.Color(0, 102, 102));
        btnApplyFilter.setForeground(new java.awt.Color(255, 255, 255));
        btnApplyFilter.setText("Apply Filter");
        btnApplyFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyFilterActionPerformed(evt);
            }
        });
        add(btnApplyFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 144, -1, -1));

        btnCancelFilter.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelFilter.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelFilter.setText("Clear Filter");
        btnCancelFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelFilterActionPerformed(evt);
            }
        });
        add(btnCancelFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 144, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = patientsTable.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please Select a row to View or Add Encounters");
        } else {
            DefaultTableModel model = (DefaultTableModel) patientsTable.getModel();
            Person selectedPerson = (Person) model.getValueAt(selectedRowIndex, 0);
            // do something with this row of data
            ViewEncounterHistory myViewHistory = new ViewEncounterHistory(rightPanel, city, personsList, selectedPerson);
            rightPanel.add("viewHistory", myViewHistory);
            CardLayout layout = (CardLayout)rightPanel.getLayout();
            layout.next(rightPanel);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        populateTable(personsList);
        populateFilter();
    }//GEN-LAST:event_formComponentShown

    private void btnApplyFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyFilterActionPerformed
        // TODO add your handling code here:
        
        // check for validations
        if (!isValidDoubleNumber(txtBloodPressure.getText())) {
            JOptionPane.showMessageDialog(this,"Blood Pressure needs numbers to filter");
            return;
        }
        
        PersonsList filteredPersonsList = new PersonsList();
        PersonsList initialList = new PersonsList();
        if (selCommunity.getSelectedItem().toString().equals("")){
            initialList = personsList;
            // do nothing
        } else {
            String selectedCommunityName = selCommunity.getSelectedItem().toString();
            Community newSelectedCommunity = new Community();
            for (Community c:city.getCommunities()){
                if (c.getName().equals(selectedCommunityName)){
                    newSelectedCommunity = c;
                    break;
                }
            }
            
            for (Person p:personsList.getPersonsList()){
             House h = p.getHouse();
             if (newSelectedCommunity.getHousesList().size() > 0 && checkHouseCommunityConnection(newSelectedCommunity, h)) {
                 initialList.add(p);
             }
            }
        }
        
        if (txtBloodPressure.getText().equals("")) { // bp filter
            // do nothing or filter nothing
            filteredPersonsList = initialList;
        } else {
            Double bp = Double.parseDouble(txtBloodPressure.getText());
            for (Person p: initialList.getPersonsList()){
                if (p.getEncounterHistory().getEncounterHistory().size() > 0) {
                    if (p.getEncounterHistory().getEncounterHistory().get(0).getVitals().getBloodPressure() > bp){
                        filteredPersonsList.add(p);
                    }
                }
            }
        }
      
      populateTable(filteredPersonsList);
      
      if(filteredPersonsList.getPersonsList().size() == 0){
           JOptionPane.showMessageDialog(this,"No Persons Found matching criteria");
      }
    }//GEN-LAST:event_btnApplyFilterActionPerformed

    private void btnCancelFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelFilterActionPerformed
        // TODO add your handling code here:
        populateTable(personsList);
        selCommunity.setSelectedItem("");
        txtBloodPressure.setText("");
    }//GEN-LAST:event_btnCancelFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyFilter;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancelFilter;
    private javax.swing.JButton btnEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JTable patientsTable;
    private javax.swing.JComboBox<String> selCommunity;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JTextField txtBloodPressure;
    // End of variables declaration//GEN-END:variables

    private void populateTable(PersonsList personsList) {
        DefaultTableModel model = (DefaultTableModel) patientsTable.getModel();
        model.setRowCount(0);
        
        for(Person p:personsList.getPersonsList()) {
           Object[] row = new Object[6];
           row[0] = p;
           row[1] = p.getAge();
           row[2] = p.getSex();
           row[3] = p.getPatientId();
           if (p.getEncounterHistory().getEncounterHistory().size()> 0){
               row[4] = p.getEncounterHistory().getEncounterHistory().get(0).getVitals().getBloodPressure();
               row[5] = p.getEncounterHistory().getEncounterHistory().get(0).getDate();
           } else {
               row[4] = "-";
               row[5] = "-";
           }
           
           model.addRow(row);
        }
    }
    
    private void populateFilter() {
        ArrayList<String> myCommunityList = new ArrayList<String>();
        myCommunityList.add("");
        
        for(Community c : city.getCommunities()) {
            // check if it is already present in the list before trying to add it to list
            if (!myCommunityList.contains(c.getName()))myCommunityList.add(c.getName());
        }
        
        // convert arraylist to array
        String[] myCommunities = myCommunityList.toArray(new String[0]);
        
        // populating the menus
        selCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(myCommunities));
    }
    
    private boolean checkHouseCommunityConnection(Community community, House house){
        boolean isIn = false;
        for (House h:community.getHousesList()){
            if (h.getHouseNumber() == house.getHouseNumber() && h.getStreetName().equals(house.getStreetName()) && h.getZipCode() == house.getZipCode()) {
                isIn = true;
            }
        }
        return isIn;
    }
    
    private boolean isValidDoubleNumber(String numberString) {
        boolean isValid = true;
        for (int i = 0; i < numberString.length(); i++) {
            char c = numberString.charAt(i);
            if (c == '.' || (c>='0' && c<='9')) {
               isValid = true; 
            } else {
                isValid = false;
            }
        }
        return isValid;
    }
}
